import mongoose from 'mongoose';

const codeSchema = new mongoose.Schema({
  code: {
    type: String,
    required: [true, 'Please add a code'],
    unique: true,
    uppercase: true,
    trim: true,
    match: [/^[A-Z0-9-]+$/, 'Code must contain only letters, numbers, and hyphens']
  },
  // Track if game has been attempted with this code
  gameAttempted: {
    type: Boolean,
    default: false,
    index: true
  },
  // Store user's selected number for lucky number game
  userNumber: {
    type: Number,
    default: null,
    min: 1,
    max: 100
  },
  // Store winning number generated by system
  winningNumber: {
    type: Number,
    default: null,
    min: 1,
    max: 100
  },
  // Game result: pending, won, lost
  gameResult: {
    type: String,
    enum: ['pending', 'won', 'lost'],
    default: 'pending',
    index: true
  },
  isUsed: {
    type: Boolean,
    default: false,
    index: true
  },
  reward: {
    type: String,
    default: 'No reward',
    enum: [
      'Free Drink 250ml',
      'Free Drink 500ml',
      '20% Discount',
      '50% Discount',
      'Free Premium Bundle',
      'Buy One Get One',
      'No reward'
    ]
  },
  usedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  usedAt: {
    type: Date,
    default: null
  },
  generatedAt: {
    type: Date,
    default: Date.now
  },
  expiresAt: {
    type: Date,
    default: () => new Date(Date.now() + 90 * 24 * 60 * 60 * 1000) // 90 days expiry
  },
  batchId: {
    type: String,
    required: true,
    index: true
  },
  qrCode: {
    type: String,
    default: null
  }
}, { timestamps: true });

// Index for faster lookups
codeSchema.index({ code: 1, gameAttempted: 1 });
codeSchema.index({ gameResult: 1, isUsed: 1 });
codeSchema.index({ createdAt: -1 });

export default mongoose.model('Code', codeSchema);
